name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v4
      - name: Setup NodeJs 13.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run image
        uses: abatilo/actions-poetry@v4
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Generate README file
        run: poetry run python main.py
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
